### ISSUE TITLE
test:easy-url is hardcoded to use localhost

### ISSUE THREAD

**Issue by dmcassel** [marklogic-community/marklogic-unit-test#119]
See definition of [`$local-url` in test-helper.xqy](https://github.com/marklogic-community/marklogic-unit-test/blob/master/marklogic-unit-test-modules/src/main/ml-modules/root/test/test-helper.xqy#L176). 

When calling `test:http-get` (or similar), it's helpful to be able to just provide a path and have the framework figure out the details -- build a URL based on the test app server. This makes it easier to test REST extensions, transforms and so. Right now, you either need to build the URL yourself or it will fail anywhere but localhost. (It's not hard to build the URL, but this would be a handy and easy thing to do.) 

I think all that's needed is to change the relevant line like this:

```
declare variable $local-url as xs:string := xdmp:get-request-protocol() || "://%%mlHost%%:" || xdmp:get-request-port();
```

**Comment by jamesagardner** [comment]
I agree that hard `$local-url` to `localhost` doesn't seem like the best solution.

I wonder how much support the framework should provide for surface area testing of MarkLogic.  I believe testing MarkLogic's external interfaces is best handled by a middle-layer testing tool (JUnit, etc.) using middle-layer connection settings (Java client API, etc).  Leaving marklogic-unit-test to focus on internal unit testing code that runs within MarkLogic.  

It is possible to invoke MarkLogic REST extensions as well as transforms without generating an HTTP request by calling internal XQuery functions.  I know it can be brittle to rely on internal functions instead of published interfaces, that's why I've been pushing for future MarkLogic interfaces to be released with methods to support unit testing.

**Comment by dmcassel** [comment]
I'd be in favor of future MarkLogic interfaces being released with methods to support testing, but until that happens, there are times when it's handy to make HTTP requests. MarkLogic Unit Test already provides support for this (the `test:http-*` functions, combined with using secure credentials); it's just broken in this one spot that would be easy to fix. If no one objects, I can send a PR with the fix.

**Comment by jamesagardner** [comment]
No objections from me @dmcassel.  A PR would be highly appreciated.

**Comment by dmcassel** [comment]
After looking at this some more, I realized that my failing tests were due to something unrelated. `localhost` actually does make sense here -- it's for code running in an app server that should generate a URL to talk to the same app server. I'm going to close this ticket and the related PR. If anyone disagrees, feel free to reopen.
