### ISSUE TITLE
Ability to copy test-data dir in one go, and easily clean up

### ISSUE THREAD

**Issue by grtjn** [marklogic-community/marklogic-unit-test#137]
It would be nice if you would not need to go search what test-data is provided within the suite, and build your own loop to copy one by one, preserving permissions, collections, etc.

Even nicer if there were a way to copy a subset per test case, and easily clean up after the test case as well.

I have some code I can share if there is interest.

**Comment by dmcassel** [comment]
I'm curious what your proposed solution would look like.

**Comment by grtjn** [comment]
PR #139.. make sure to read the comment.. ;)

**Comment by grtjn** [comment]
@dmcassel, WDYT?

**Comment by rjrudin** [comment]
There's definitely good value here, as the user need of "Load some data (in a separate transaction) before this test runs" is common - there's a good bit of plumbing in the DHF marklogic-unit-test tests to do exactly that. And that's different from the user need of "Load these documents before any tests run so that they're available for all tests" - mlDeploy can satisfy that need via e.g. src/test/ml-data. But that's a separate need. 

I'm wondering though if there's an easy button to provide for users so that they can avoid multi-statement XQuery modules? Those are a bit more complex and run counter to the current pattern of "Look in the setup/teardown modules to find setup/teardown stuff". 

For example, here's what a setup.xqy module looks like in DHF that both clears out some data and loads some test-specific data:

```
xquery version "1.0-ml";
import module namespace hub-test = "http://marklogic.com/data-hub/test" at "/test/data-hub-test-helper.xqy";
hub-test:reset-hub();

xquery version "1.0-ml";
import module namespace hub-test = "http://marklogic.com/data-hub/test" at "/test/data-hub-test-helper.xqy";
import module namespace test = "http://marklogic.com/test" at "/test/test-helper.xqy";
hub-test:load-artifacts($test:__CALLER_FILE__),
hub-test:load-jobs($test:__CALLER_FILE__)
```

I think multi-statement setup modules are fine because we don't have to parse out what's the setup logic and what's the actual test logic. 

What seems even better though is if MLUT just loaded the data (if detected for a particular test module) automatically via separate transactions. Then the user doesn't need any new code - they just add their data files and collections/permissions and they're off and running.

**Comment by rjrudin** [comment]
I'm closing this for now until a request like this pops up again. With the docs we have for loading data, I think this is already pretty easy for a user to do - just toss some basic code into the setup or suite setup, where it's also easy to configure permissions and collections. We'd need to invent a way otherwise for permissions/collections to be configured for the test-data documents. 

Also, my preference is not to delete data after a test ends - that allows for easier debugging if the test fails, as well as manual inspection of how data was modified. I prefer for data to be deleted before a test begins instead.
