### ISSUE TITLE
Improve readability on testreports in cicd pipelines 

### ISSUE THREAD

**Issue by peetkes** [marklogic-community/marklogic-unit-test#181]
To improve the readability on the test reports in CICD pipelines the attribute classname of the testcase element should contain the name attribute of the parent (testsuite)
See below for a screenshot of the testreport in Gitlab CICD pipeline:
![Screenshot 2023-08-10 at 11 24 40](https://github.com/marklogic-community/marklogic-unit-test/assets/550788/114eeb41-393b-4ceb-9155-31dc67450540)
It does not make sense to have the classname and name of the testcase to reflect the same name.
GitLab takes the classname and labels it 'Suite'

This can be done in j-unit.xsl stylesheet by passing in the suite name as a parameter, line 23 and further:
```
	<xsl:template match="test:suite">
		<testsuite errors="0" failures="{@failed}" hostname="{$hostname}" name="{@name}" tests="{@total}" time="{@time}" timestamp="{$timestamp}">
			<xsl:apply-templates>
                                 <xsl:with-param name="suite" tunnel="yes" select="@name"/>
                         </xsl:apply-templates>
		</testsuite>
	</xsl:template>

	<!-- Output test cases within test suites -->
	<xsl:template match="test:test">
                 <xsl:param name="suite" select="@name" tunnel="yes"/>
		<testcase classname="{$suite}" name="{@name}" time="{@time}">
			<xsl:apply-templates/>
		</testcase>
	</xsl:template>
```

**Comment by rjrudin** [comment]
In JUnit, `classname` = the name of the Java class, and `name` = the name of the method in the Java class.

So for marklogic-unit-test, where a single file is a single test (with 1 to many assertions), a directory is then equivalent to a Java class in JUnit. 

So this makes good sense - `classname` should be the name of the suite directory, and `name` should be the name of the test file.

**Comment by rjrudin** [comment]
I'm looking at this again, and now I'm questioning what GitLab is doing. 

Given the following JUnit XML:

```
<testsuite errors="0" failures="1" hostname="localhost" name="My Tests" tests="2" time="0.261226" timestamp="">
  <testcase classname="example-failing-tests.xqy" name="example-failing-tests.xqy" time="0.12342">
```

It is using the value `testcase/@classname` and calling it "Suite". But there's an element called `testsuite` with a `@name` attribute - surely that is what the "Suite Name" should be, right? 

Via your proposal and PR - #183 - the following XML is now being produced:

```
<testsuite errors="0" failures="1" hostname="localhost" name="My Tests" tests="2" time="0.233369" timestamp="">
  <testcase classname="My Tests" name="example-failing-tests.xqy" time="0.111941">
```

I don't think saying that "suite name" and "classname" are equivalent is the right approach though. For a regular set of e.g. JUnit tests, the labels used in Jenkins test reports are:

- test suite name -> the Java package name (analogous to a directory name)
- test class name -> the Java class name
- test name -> the name of the method in the Java class

marklogic-unit-test lacks the concept of a "test method". So marklogic-unit-test either needs to conflate "classname" and "test name", or conflate "suite name" and "class name". But since marklogic-unit-test clearly has the concepts of a suite being a directory of tests, and each file being a test case, I think marklogic-unit-test has to have the following mapping:

- test suite name = the directory name - e.g. "My Tests"
- test class name = the filename
- test name = also the filename

Besides, changing this mapping would clearly be a breaking change and would require a major release. Can definitely consider that for a 2.0 - I'd certainly like to clear up the use of the term "tests" instead of "assertions" - but it's not doable now, nor do I think we should do it now.
