### ISSUE TITLE
Support testing of REST services

### ISSUE THREAD

**Issue by damonfeldman** [marklogic-community/marklogic-unit-test#25]
Support adding data and accessing it via REST. This would naturally include testing out of the box REST Services (/v1/...) as well as REST with transforms or options nodes, and REST Extensions (backed by code).

This differs from unit testing mostly in that it includes the rewriter, batching, URL formatting, headers, security, SSL and the network, load balancers and other non-MarkLogic infrastructure components.

**Comment by jamesagardner** [comment]
I believe that between `xdmp:http-get` and the inclusion of `marklogic-junit5` into the project we have plenty of ways to exercise `/v1/...` extensions.

I think to add additional support we would need to work with product engineering to expose access to the HTTP request arguments and response types so that we can better inject and inspect incoming and outgoing payload details from within the server itself.  I'm pretty sure the preferred direction is to use tooling external to the MarkLogic e-node to perform these types of tests and `marklogic-junit5` has tooling to do so.
