### ISSUE TITLE
Document How To Identify Why a Test Failed

### ISSUE THREAD

**Issue by jamesagardner** [marklogic-community/marklogic-unit-test#63]
Document the general pattern:

1. Run suite of tests, some fail
1. Use UI to run individual test
    - be sure to uncheck teardown
1. Use qconsole to inspect database state
1. Use log statements and error logs to get insight into the run time
   - would be great to have the debugger working here

Getting feedback while updating tests:
1. Run `gradle mlWatch`
1. Make changes in editor of choice
1. Run test using UI code

**Comment by joecrean** [comment]
on point 2. 


2. Use UI to run individual test
     * click open the failing test in the UI in order to view the stack trace which will show which test has failed. 
     * be sure to uncheck teardown to view the state of the test data at the time of failure.
 
on point 4.

4. Use log statements and error logs to get insight into the run time (tip: if you are testing a REST extension, your test code may be running in a different application server as the application code)
     * would be great to have the debugger working here

**Comment by damonfeldman** [comment]
We identified two main testing patterns in other discussions, which should be documented. These show people both how to debug test failures, and also how to do test-driven development in MarkLogic in the first place.

Fortunately MarkLogic is more functional and componentized than a typical Java project, making it very natural to test components in DHF in particular. Each of the following is a natural, test-able component.

- DHF plugins
- declarative mapper mappings
- TDEs
- Redaction configuration
- REST API transforms
- and the like. For someone using marklogic-unit-test (preferred) the way to actually test and debug is to either

1. Edit and review in an interactive cycle
   - Edit the tests in some editor
   - Have "gradle mlWatch" running so those edits are pushed immediately
   - Have the testing web page open ( http://localhost:8042/test/default.xqy ) to run one test, or many there
   - Have the log file for your app server open (8042_ErrorLog.txt) so you can see new log statements that you add/tweak

2. Manually run setup + test in qconsole
   - do an xdmp.invoke(of the setup) - it can't run from qconsole because the module location it is run from matters.
   - run the test in qconsole, and return/log interesting info, or tweak the test in real-time in qconsole

**Comment by jmakeig** [comment]
> 2\. Manually run setup + test in qconsole

I don’t think we should recommend that. We should recommend a proper test harness and make using that easier than pasting into Query Console.

**Comment by jamesagardner** [comment]
I agree with @jmakeig.  I don't think reproducing the test context in Query Console is the right long term approach.  Query Console is a great place to investigate the database state after a test run, but it's not a well suited run time for tests that may have complex setups and interdependencies.

**Comment by rhdunn** [comment]
With my IntelliJ XQuery plugin, I am planning on adding support for running marklogic-unit-test based tests using the test runner framework to handle setup/teardown. These would provide the same workflow and UI/UX as the JUnit based tests.

I'm also planning on adding debugging support for MarkLogic queries, allowing you to debug any issues.

I have support for running (and profiling) queries in MarkLogic in the 1.4.1 version for IntelliJ 2019.1. Using the "Active editor file" option for the query file, I can currently run tests that don't have any setup/teardown requirements.

Errors are displayed in the output with the values from the assert and the stack trace of the function calls. This does not currently link to the files in the editor (like with Java stack traces), but this is something I am looking to implement.

**Comment by pne** [comment]
My go-to for figuring out which test failed is to dive into build/test-results/marklogic-unit-test and look at the TEST-*.xml files.

**Comment by rjrudin** [comment]
This would be a good addition to our new docs.

**Comment by rjrudin** [comment]
DEVEXP-554
