### ISSUE TITLE
outcome of all passing assertions do not increment counters in UI when running sjs unittests

### ISSUE THREAD

**Issue by peetkes** [marklogic-community/marklogic-unit-test#64]
I just added the ml-unittest plugin in my dhf project and started writing unittests.
This is an sjs project from start to finish so i started writing my first unittests in sjs and hit the unittest UI.
When all my assertions succeed the number of counts in the UI does not reflect the total number of assertions.
My code looks like this:
````
'use strict';

const test = require('/test/test-helper.xqy');

function testImportLookup() {
    return  [
        test.assertEqual(fn.true(), fn.true()),
        test.assertEqual(fn.false(), fn.false())
    ];
}

const assertions = [];

assertions.push(testImportLookup());

assertions
````
So the assertions look like this when I run it in qconsole
````
[
[
"<t:result type=\"success\" xmlns:t=\"http://marklogic.com/roxy/test\"/>", 
"<t:result type=\"success\" xmlns:t=\"http://marklogic.com/roxy/test\"/>"
]
]
````

**Comment by jamesagardner** [comment]
Further investigation suggests that this is influenced by what the SJS module returns.  If the SJS module returns the contents of an assert function it seems to credit the test as passing, but if it returns something different it fools the runner into not incrementing the `t:suite/@passed` attribute.  The test UI shouldn't be dependent on the test module returning the contents of assert functions.

**Comment by dmcassel** [comment]
I think the problem is that the array you're returning isn't flat. Try making it so that the array contains the t:result elements directly, instead of containing a second level of arrays.

**Comment by jamesagardner** [comment]
@dmcassel is correct that it's the nested array causing the issue witnessed.

@peetkes the following code that flattens the assertions array seems to do the trick for me:

```
'use strict';

const test = require('/test/test-helper.xqy');

function testImportLookup() {
    return  [
        test.assertEqual(fn.true(), fn.true()),
        test.assertEqual(fn.false(), fn.false())
    ];
}

const assertions = [];

assertions.push(testImportLookup());

[].concat.apply([], assertions);
```

Despite the above work around I believe we should change the way we determine if a test is passing or failing.  I believe the framework shouldn't rely on the automated test to return success / failure data.  I believe the framework should count any test that doesn't error out as a single success.  I believe the framework should count any test that throws an assertion error should be counted as a single failure.  This pass/fail approach is already supported by the current assertion functions since they all return exceptions when they fail.  I'm OK with returning success data on tests passing, in case someone ever wanted to document and do something meaningful with that data, but I don't believe the framework should be reliant on it.

I think this would change the way the UI counts successes (only 1 success per test, instead of 1 success for each assertion returned by the test).   I've never liked the current way the UI counts successes because it's inconsistent, which I find confusing.  If a test has 5 assertions, and they all succeed it will report a total test count of 1, with 5 test runs and 5 passed.  However, if the same test has a single failure, it will report a total test count of 1, with 1 test run and 1 failure.  The test run numbers should not change for a given test regardless of if it passes or fails, and I believe they should not exceed the total test count.

I believe my proposed change in how how we account for passing/failing tests will bring marklogic-unit-test more in-line with other automated testing frameworks like JUnit, which only count a test once, regardless of how many assertions are made within that test.

@rjrudin, @dmcassel, @hansenmc what are your thoughts on changing the way marklogic-unit-test counts test successes and failures?

**Comment by hansenmc** [comment]
I would be okay with that change. 

I guess it comes down to how to organize and count tests. Should there be one test per test module? 

I would rather that our test modules were more like JUnit or XRay, in which you have a test file(module) that can have multiple test functions (identified by [annotations ](https://docs.marklogic.com/guide/xquery/enhanced#id_94002) and/or naming conventions), and each of those functions must have at least one test assertion.

**Comment by jmakeig** [comment]
Most test frameworks that I’ve used in the JavaScript world count assertions, not tests. Tests are just a way of grouping them with a name and optionally some setup/teardown logic.

**Comment by rjrudin** [comment]
I am removing this from 1.0 under the assumption that nothing was done for it, and 1.0 was released already

**Comment by rjrudin** [comment]
Not going to change how things are counted in the 1.x timeframe, that would be a breaking change. 

Food for thought though - with JUnit, and pytest, and other similar frameworks, each test file has multiple actual "tests" in it. Each test performs 1->many assertions. The frameworks count the number of tests. In my experience, the number of actual assertions is a bit irrelevant - it's like counting lines of code, it doesn't really reflect how "good" the test is. 

marklogic-unit-test only has the concept of a "test file with 1 to many assertions". So I think each test file corresponds to what JUnit/pytest consider to be a single "test".

**Comment by dmcassel** [comment]
@rjrudin 

> the number of actual assertions is a bit irrelevant - it's like counting lines of code, it doesn't really reflect how "good" the test is

I don't think I agree with this. A test case that makes one assertion is probably less "good" than one that makes 20 or 50, don't you think? (The issue is closed, so no pressure to continue this discussion, just catching up.)
