### ISSUE TITLE
Document Unit Testing Data Hub Framework (DHF) Flow

### ISSUE THREAD

**Issue by jamesagardner** [marklogic-community/marklogic-unit-test#65]
We need examples and documentation on a pattern for invoking and testing the content, header, and triple modules that would exist as a part of a DHF flow.  Ideally the example would happen at a unit level, and exist entirely in MarkLogic.

SJS and XQuery examples would be great.

**Comment by joecrean** [comment]
@jamesagardner 
i think there is a bit of a crossover here. Do we want to pull DHF in here ? maybe not. Maybe that would be better in DHF itself. Referring to @rjrudin's work on DHF/Unit test in [this ticket](https://github.com/marklogic-community/marklogic-unit-test/issues/26) and the commentary there I think it would be a good idea to built unit test directly into DHF and have all the test resources deployed automatically but that is maybe a separate discussion. In any case I will start with some code to demonstrate some approaches to creating tests on previously harmonised documents. Realistically you would invoke the DHF input/harmonisation in test setup. I will leave that open for the moment because if we go down that route then we will need to pull in DHF.. I have code to invoke flows etc etc .. for me it is just a matter of where is best to show this.

**Comment by dmcassel** [comment]
+1 that DHF-specific documentation and examples belong in DHF.

**Comment by jamesagardner** [comment]
@joecrean I agree with that thought process.  I definitely wouldn't want to import DHF into this project.  Let's go ahead and move the work into the DHF project.  Maybe we could mention and link to examples that live in the DHF project in case someone is looking around this project for DHF testing examples.

**Comment by joecrean** [comment]
@jamesagardner @dmcassel 
I did a quick inventory over on the DHF GitHub and there are two examples of flows with tests under [DHF4 with tests js only](https://github.com/marklogic/marklogic-data-hub/tree/master/examples/dhf4-with-tests-javascript-only) and [DHF4 with tests](https://github.com/marklogic/marklogic-data-hub/tree/master/examples/dhf4-with-tests) (which is also JS only but is intended to show the JUnit client capability).. These examples have a small flow predefined and demonstrate some testing. The setup does not run the flow, it just prepares data. 
Maybe there could be more example tests... maybe they could be restructured differently - i like a declarative style where you can easily see what is being tested. There could be some xquery examples. Above all we could pull in @rjrudin's work so that when you deploy this example you get the test dbs, app server etc. That would be the big picture. Basically if you fire up a DHF project today and want unit testing (and we should encourage this i think ) then you have to pull in stuff from all over the place before you have everything in place. Maybe we could fix this here and I mean over on DHF.. what say you?

**Comment by dmcassel** [comment]
@joecrean I'm not clear what you're proposing. The dhf4-with-tests-javascript-only example project has the `build.gradle` entries needed to bring in the marklogic-unit-test library, as well as examples of writing those tests. I agree that it's good to encourage testing, but I'm not sure what you mean by " you have to pull in stuff from all over the place before you have everything in place". The purpose of splitting marklogic-unit-test out of Roxy was to make it easy to include in gradle-based projects, which I think it's accomplished (hurray Rob!)

**Comment by joecrean** [comment]
@dmcassel 
hey Dave, firstly I hope I am not stepping on anyone's toes - not at all my intention. The example is as you say and pretty useful. IMHO what is missing is the stuff from Rob's work (linked above) which shows how to create test dbs and app servers. That's why IMHO it is not enough just to pull in the unit test framework you need the test artifacts as well... basically like it was in roxy.. if you set the test port then everything was created for you. Hope I have not misunderstood something on the way here. On Monday I will have a look at expanding the example in DHF or even adding a new one.

**Comment by dmcassel** [comment]
@joecrean not at all -- I'm glad to see the interest in continuing to improve this project! I do want to see this project remain independent of DHF, as it's useful for any MarkLogic-based project that uses ml-gradle. 

I think you're suggesting more info for the [How to Include ML Unit Test in Your Project](https://marklogic-community.github.io/marklogic-unit-test/include/), but more DHF-specific. Is that right? That shows how to add this project to DHF and what properties you need to set, but with DHF's more complex environment, maybe that's not enough. What about a page under [DHF Tools](https://marklogic.github.io/marklogic-data-hub/tools/) that talks about any DHF-specific configuration or testing consideration?

**Comment by derms** [comment]
@joecrean fyi https://github.com/marklogic/marklogic-data-hub/tree/master/examples/dhf4-with-tests-javascript-only does actually run the flows. The flow is executed 100% in javascript. 

the suite is entirely self contained.

**Comment by jamesagardner** [comment]
@derms that project seems very useful.  Has anyone put thought into production an mlBundle to publish the [dhfTestUntils.sjs](https://github.com/marklogic/marklogic-data-hub/blob/master/examples/dhf4-with-tests-javascript-only/src/test/ml-modules/root/test/lib/dhfTestUtils.sjs) in a way that other projects could use those functions?

It looks like there are examples out there for running a DHF flow, as well as examples for invoking specific pieces of the DHF flow from a unit test.  Perhaps we can work on bundling up the helper functions and publish them so that people who are doing unit testing within DHF can take advantages of already written and maintained helper libraries that make it easier to test their DHF flow.  We should have automated tests in the DHF project to make sure the helper library works with the latest DHF code.

@joecrean does packaging up the helper, and putting together tests against such a helper sound like something you'd be interested in working on?  If so I think we should work to create an issue in the DHF project for you to work on.

Unless someone objects I'm thinking this issue could be closed, unless someone can provide a specific documentation need that we can use this issue for.

**Comment by jamesagardner** [comment]
This is being tracked at https://github.com/marklogic/marklogic-data-hub/issues/2125
